Repository fortran-lang/stdlib, pull requests merged in 2021-05, with the labels that each got.

#359 Add general contributing guidelines to stdlib
  CONTRIBUTING.md
  README.md
  doc/contributing/index.md
Labels: documentation, meta, reviewers needed

#355 implemented clip function
  doc/specs/stdlib_math.md
  src/CMakeLists.txt
  src/Makefile.manual
  src/stdlib_math.fypp
  src/tests/CMakeLists.txt
  src/tests/Makefile.manual
  src/tests/math/CMakeLists.txt
  src/tests/math/Makefile.manual
  src/tests/math/test_stdlib_math.f90
Labels: reviewers needed

#407 changed to_title to to_sentence and implemented correct to_title
  doc/specs/stdlib_ascii.md
  doc/specs/stdlib_string_type.md
  src/Makefile.manual
  src/stdlib_ascii.fypp
  src/stdlib_string_type.fypp
  src/tests/ascii/test_ascii.f90
  src/tests/string/test_string_functions.f90
Labels: reviewers needed

#415 Corrected Ubuntu version
  README.md
Labels: reviewers needed

#417 Add GCC-11 to workflow
  .github/workflows/CI.yml
  CMakeLists.txt
  README.md
Labels: compilers, reviewers needed
