Repository fortran-lang/stdlib, pull requests merged in 2021-09, with the labels that each got.

#511 Correctly set CMAKE_INSTALL_MODULEDIR cache variable
  config/CMakeLists.txt
Labels: bug, reviewers needed

#513 Update issue templates
  .github/ISSUE_TEMPLATE/01_bug.md
  .github/ISSUE_TEMPLATE/01_bug.yaml
  .github/ISSUE_TEMPLATE/02_proposal.md
  .github/ISSUE_TEMPLATE/02_proposal.yaml
  .github/ISSUE_TEMPLATE/03_free.md
  .github/ISSUE_TEMPLATE/config.yaml
Labels: meta, reviewers needed

#475 Generating sorting subroutines specific to `character` type with fypp
  src/stdlib_sorting.fypp
  src/stdlib_sorting_ord_sort.fypp
  src/stdlib_sorting_sort.fypp
  src/stdlib_sorting_sort_index.fypp
Labels: reviewers needed

#529 Add maintainer entry to fpm manifest
  ci/fpm.toml
Labels: build: fpm, automation

#530 Make it clearer how the user can control compiler optimization
  Makefile.manual
  README.md
Labels: documentation, reviewers needed, build: cmake, build: make

#528 Reduce redundancy caused by optional arguments
  src/stdlib_bitsets.fypp
  src/stdlib_bitsets_64.fypp
  src/stdlib_bitsets_large.fypp
  src/stdlib_logger.f90
  src/stdlib_sorting.fypp
  src/stdlib_sorting_ord_sort.fypp
  src/stdlib_sorting_sort.fypp
  src/stdlib_sorting_sort_index.fypp
  src/stdlib_stats_distribution_PRNG.fypp
  src/stdlib_stats_moment_all.fypp
  src/stdlib_string_type.fypp
Labels: reviewers needed, refactoring
