Repository fortran-lang/stdlib, pull requests merged in 2021-12, with the labels that each got.

#500 Selection algorithms
  doc/specs/stdlib_selection.md
  src/CMakeLists.txt
  src/Makefile.manual
  src/stdlib_selection.fypp
  src/tests/CMakeLists.txt
  src/tests/Makefile.manual
  src/tests/selection/CMakeLists.txt
  src/tests/selection/Makefile.manual
  src/tests/selection/test_selection.fypp
Labels: topic: algorithms

#581 Add routines for saving/loading arrays in npy format
  doc/specs/stdlib_io.md
  src/CMakeLists.txt
  src/Makefile.manual
  src/stdlib_io_npy.fypp
  src/stdlib_io_npy_load.fypp
  src/stdlib_io_npy_save.fypp
  src/tests/io/CMakeLists.txt
  src/tests/io/Makefile.manual
  src/tests/io/test_npy.f90
Labels: topic: IO

#590 Update changelog
  CHANGELOG.md
  CONTRIBUTING.md
Labels: documentation, reviewers needed

#588 Error on no tests in CTest
  .github/workflows/CI.yml
  ci/install_cmake.sh
Labels: reviewers needed, build: cmake

#591 Fix compilation errors with makefiles due to command-line variable assignments
  .github/workflows/CI.yml
  Makefile.manual
  README.md
Labels: build: make

#273 Probability Distribution and Statistical Functions -- Normal Distribution Module
  doc/specs/index.md
  doc/specs/stdlib_stats_distribution_normal.md
  src/CMakeLists.txt
  src/Makefile.manual
  src/stdlib_stats_distribution_normal.fypp
  src/tests/stats/CMakeLists.txt
  src/tests/stats/Makefile.manual
  src/tests/stats/test_distribution_normal.fypp
Labels: reviewers needed, topic: statistics

#584 Replace the call to sort by select in stdlib_stats_median
  doc/specs/stdlib_stats.md
  src/Makefile.manual
  src/stdlib_stats_median.fypp
  src/tests/stats/test_median.fypp
Labels: reviewers needed

#594 Minor update to makefile installation instructions
  README.md
Labels: documentation, build: make

#596 Rename references to default branch
  API-doc-FORD-file.md
  CONTRIBUTING.md
  STYLE_GUIDE.md
  src/stdlib_selection.fypp
Labels: meta

#600 Fix iomsg allocation in save_npy
  src/stdlib_io_npy_save.fypp
  src/tests/io/test_npy.f90
Labels: reviewers needed

#488 [stdlib_math] add `is_close` routines.
  doc/specs/stdlib_math.md
  src/CMakeLists.txt
  src/Makefile.manual
  src/stdlib_math.fypp
  src/stdlib_math_all_close.fypp
  src/stdlib_math_arange.fypp
  src/stdlib_math_is_close.fypp
  src/tests/math/test_stdlib_math.fypp
Labels: topic: mathematics, reviewers needed

#597 Add getline to read whole line from formatted unit
  CHANGELOG.md
  doc/specs/stdlib_io.md
  src/Makefile.manual
  src/stdlib_io.fypp
  src/tests/io/CMakeLists.txt
  src/tests/io/Makefile.manual
  src/tests/io/test_getline.f90
Labels: topic: IO

#498 [stdlib_math] add `arg/argd/argpi`
  CHANGELOG.md
  doc/specs/stdlib_math.md
  src/stdlib_math.fypp
  src/tests/math/Makefile.manual
  src/tests/math/test_stdlib_math.fypp
Labels: topic: mathematics

#603 Implement trueloc/falseloc
  CHANGELOG.md
  doc/specs/index.md
  doc/specs/stdlib_array.md
  src/CMakeLists.txt
  src/Makefile.manual
  src/stdlib_array.f90
  src/tests/CMakeLists.txt
  src/tests/Makefile.manual
  src/tests/array/CMakeLists.txt
  src/tests/array/Makefile.manual
  src/tests/array/test_logicalloc.f90
Labels: topic: utilities, reviewers needed

#573 Revised Hash functions incorporating changes in the main Stdlib repository.
  .github/workflows/CI.yml
  CHANGELOG.md
  CMakeLists.txt
  Makefile.manual
  ci/fpm-deployment.sh
  doc/specs/index.md
  doc/specs/stdlib_hash_procedures.md
  src/CMakeLists.txt
  src/Makefile.manual
  src/stdlib_hash_32bit.fypp
  src/stdlib_hash_32bit_fnv.fypp
  src/stdlib_hash_32bit_nm.fypp
  src/stdlib_hash_32bit_water.fypp
  src/stdlib_hash_64bit.fypp
  src/stdlib_hash_64bit_fnv.fypp
  src/stdlib_hash_64bit_pengy.fypp
  src/stdlib_hash_64bit_spookyv2.fypp
  src/tests/CMakeLists.txt
  src/tests/Makefile.manual
  src/tests/hash_functions/CMakeLists.txt
  src/tests/hash_functions/Makefile.manual
  src/tests/hash_functions/README.md
  src/tests/hash_functions/SpookyV2.cpp
  src/tests/hash_functions/SpookyV2.h
  src/tests/hash_functions/SpookyV2Test.cpp
  src/tests/hash_functions/generate_hash_arrays.cpp
  src/tests/hash_functions/nmhash.c
  src/tests/hash_functions/nmhash.h
  src/tests/hash_functions/nmhash_scalar.c
  src/tests/hash_functions/nmhash_scalar.h
  src/tests/hash_functions/pengyhash.c
  src/tests/hash_functions/pengyhash.h
  src/tests/hash_functions/test_hash_functions.f90
  src/tests/hash_functions/waterhash.c
  src/tests/hash_functions/waterhash.h
  src/tests/hash_functions_perf/CMakeLists.txt
  src/tests/hash_functions_perf/Makefile.manual
  src/tests/hash_functions_perf/test_32_bit_hash_performance.f90
  src/tests/hash_functions_perf/test_64_bit_hash_performance.f90
Labels: topic: algorithms

#610 Fixed tables in stdlib_hash_procedures.md
  doc/specs/stdlib_hash_procedures.md
Labels: reviewers needed

#499 [stdlib_linalg] matrix property checks
  doc/specs/stdlib_linalg.md
  src/Makefile.manual
  src/stdlib_linalg.fypp
  src/tests/linalg/CMakeLists.txt
  src/tests/linalg/Makefile.manual
  src/tests/linalg/test_linalg_matrix_property_checks.fypp
Labels: topic: mathematics, waiting for OP
