Repository fortran-lang/stdlib, pull requests merged in 2021-10, with the labels that each got.

#539 Add function gcd
  doc/specs/stdlib_math.md
  src/stdlib_math.fypp
  src/tests/math/test_stdlib_math.f90
Labels: topic: mathematics, reviewers needed

#521 Ensure module output directory is generated in configure stage
  src/CMakeLists.txt
Labels: build: cmake

#545 Rename stdlib_stats_distribution_PRNG to stdlib_random
  CHANGELOG.md
  doc/specs/index.md
  doc/specs/stdlib_random.md
  src/CMakeLists.txt
  src/Makefile.manual
  src/stdlib_random.fypp
  src/tests/stats/test_distribution_PRNG.f90
Labels: reviewers needed, topic: statistics, refactoring

#538 Bump stdlib version to 0.1.0
  CHANGELOG.md
  CMakeLists.txt
  ci/fpm.toml
  doc/changelog.md
Labels: help wanted

#549 Make `linspace` and `logspace` pure functions
  doc/specs/stdlib_math.md
  src/stdlib_math.fypp
  src/stdlib_math_linspace.fypp
Labels: topic: mathematics

#272 Probability Distribution and Statistical Functions -- Uniform Distribution Module
  doc/specs/index.md
  doc/specs/stdlib_stats_distribution_uniform.md
  src/CMakeLists.txt
  src/Makefile.manual
  src/stdlib_stats_distribution_uniform.fypp
  src/tests/stats/CMakeLists.txt
  src/tests/stats/Makefile.manual
  src/tests/stats/common.fypp
  src/tests/stats/test_distribution_uniform.fypp
Labels: reviewers needed, topic: statistics
