Repository fortran-lang/stdlib, pull requests merged in 2021-06, with the labels that each got.

#408 Sorting2
  doc/specs/index.md
  doc/specs/stdlib_sorting.md
  src/CMakeLists.txt
  src/Makefile.manual
  src/common.fypp
  src/stdlib_sorting.fypp
  src/stdlib_sorting_ord_sort.fypp
  src/stdlib_sorting_sort.fypp
  src/stdlib_sorting_sort_index.fypp
  src/tests/CMakeLists.txt
  src/tests/Makefile.manual
  src/tests/sorting/CMakeLists.txt
  src/tests/sorting/Makefile.manual
  src/tests/sorting/test_sorting.f90
Labels: reviewers needed

#418 Improved support for NAG
  src/stdlib_logger.f90
  src/stdlib_string_type.fypp
  src/tests/logger/test_stdlib_logger.f90
  src/tests/stats/test_mean_f03.f90
Labels: compilers

#422 Minor fixes to sorting documentation
  doc/specs/stdlib_sorting.md
  src/stdlib_sorting.fypp
Labels: documentation

#430 Remove support for GCC 7 and 8
  .github/workflows/CI.yml
  .github/workflows/ci_windows.yml
  CMakeLists.txt
  README.md
  src/stdlib_string_type.fypp
Labels: compilers, reviewers needed

#424 Add separate logical kind parameters
  doc/specs/index.md
  doc/specs/stdlib_kinds.md
  src/common.fypp
  src/stdlib_ascii.fypp
  src/stdlib_kinds.f90
  src/stdlib_string_type.fypp
  src/tests/ascii/test_ascii.f90
  src/tests/string/test_string_assignment.f90
Labels: reviewers needed

#414 implemented intelligent slice functionality
  doc/specs/stdlib_string_type.md
  doc/specs/stdlib_strings.md
  src/Makefile.manual
  src/stdlib_strings.f90
  src/tests/string/test_string_functions.f90
Labels: reviewers needed

#428 Issue with stdlib_sorting
  src/stdlib_sorting_ord_sort.fypp
  src/stdlib_sorting_sort_index.fypp
  src/tests/sorting/test_sorting.f90
Labels: reviewers needed

#419 Allow modification of install directory for module files
  config/CMakeLists.txt
  config/template.pc
  src/CMakeLists.txt
Labels: reviewers needed

#432 Outer product
  doc/specs/stdlib_linalg.md
  src/CMakeLists.txt
  src/Makefile.manual
  src/stdlib_linalg.fypp
  src/stdlib_linalg_outer_product.fypp
  src/tests/linalg/test_linalg.f90
Labels: reviewers needed

#313 legendre polynomials and gaussian quadrature
  doc/specs/stdlib_quadrature.md
  doc/specs/stdlib_specialfunctions.md
  src/CMakeLists.txt
  src/Makefile.manual
  src/stdlib_quadrature.fypp
  src/stdlib_quadrature_gauss.f90
  src/stdlib_specialfunctions.f90
  src/stdlib_specialfunctions_legendre.f90
  src/tests/quadrature/CMakeLists.txt
  src/tests/quadrature/Makefile.manual
  src/tests/quadrature/test_gauss.f90
Labels: reviewers needed
