Repository fortran-lang/stdlib, pull requests merged in 2021-11, with the labels that each got.

#558 Pin specific fpm version
  .github/workflows/fpm-deployment.yml
Labels: build: fpm

#556 fix some FORD links
  doc/specs/stdlib_stringlist_type.md
Labels: documentation, reviewers needed

#494 Add testing module to allow better structuring of test suites
  ci/fpm-deployment.sh
  ci/fpm.toml
  config/CMakeLists.txt
  config/cmake/Findtest-drive.cmake
  src/stdlib_io.fypp
  src/tests/CMakeLists.txt
  src/tests/Makefile.manual
  src/tests/Makefile.manual.test.mk
  src/tests/ascii/test_ascii.f90
  src/tests/bitsets/test_stdlib_bitset_64.f90
  src/tests/bitsets/test_stdlib_bitset_large.f90
  src/tests/io/Makefile.manual
  src/tests/io/array1.dat
  src/tests/io/array2.dat
  src/tests/io/array3.dat
  src/tests/io/array4.dat
  src/tests/io/array5.dat
  src/tests/io/test_loadtxt.f90
  src/tests/io/test_loadtxt_qp.f90
  src/tests/io/test_open.f90
  src/tests/io/test_parse_mode.f90
  src/tests/io/test_savetxt.f90
  src/tests/io/test_savetxt_qp.f90
  src/tests/linalg/test_linalg.f90
  src/tests/math/test_linspace.f90
  src/tests/math/test_logspace.f90
  src/tests/math/test_math_arange.f90
  src/tests/math/test_stdlib_math.f90
  src/tests/optval/test_optval.f90
  src/tests/quadrature/test_gauss.f90
  src/tests/quadrature/test_simps.f90
  src/tests/quadrature/test_trapz.f90
  src/tests/sorting/test_sorting.f90
  src/tests/stats/CMakeLists.txt
  src/tests/stats/Makefile.manual
  src/tests/stats/common.fypp
  src/tests/stats/test_distribution_PRNG.f90
  src/tests/stats/test_mean.f90
  src/tests/stats/test_mean.fypp
  src/tests/stats/test_mean_f03.f90
  src/tests/stats/test_mean_f03.fypp
  src/tests/stats/test_median.fypp
  src/tests/stats/test_moment.f90
  src/tests/stats/test_random.f90
  src/tests/stats/test_rawmoment.f90
  src/tests/stats/test_var.f90
  src/tests/stats/test_varn.f90
  src/tests/string/test_string_assignment.f90
  src/tests/string/test_string_derivedtype_io.f90
  src/tests/string/test_string_functions.f90
  src/tests/string/test_string_intrinsic.f90
  src/tests/string/test_string_match.f90
  src/tests/string/test_string_operator.f90
  src/tests/string/test_string_strip_chomp.f90
  src/tests/string/test_string_to_string.f90
  src/tests/system/CMakeLists.txt
  src/tests/system/test_sleep.f90
Labels: reviewers needed, refactoring

#565 Make support for quadruple precision optional
  .github/workflows/CI.yml
  CMakeLists.txt
  ci/fpm-deployment.sh
  ci/fpm.toml
  config/CMakeLists.txt
  config/cmake/Findtest-drive.cmake
  config/template.cmake
  doc/specs/stdlib_kinds.md
  src/CMakeLists.txt
  src/Makefile.manual
  src/common.fypp
  src/stdlib_io.fypp
  src/stdlib_kinds.f90
  src/stdlib_kinds.fypp
  src/stdlib_linalg.fypp
  src/stdlib_math.fypp
  src/stdlib_optval.fypp
  src/stdlib_quadrature.fypp
  src/stdlib_sorting.fypp
  src/stdlib_specialfunctions.f90
  src/stdlib_stats.fypp
  src/stdlib_strings.fypp
  src/tests/CMakeLists.txt
  src/tests/Makefile.manual
  src/tests/io/CMakeLists.txt
  src/tests/io/Makefile.manual
  src/tests/io/test_loadtxt_qp.fypp
  src/tests/io/test_savetxt_qp.fypp
  src/tests/linalg/CMakeLists.txt
  src/tests/linalg/Makefile.manual
  src/tests/linalg/test_linalg.fypp
  src/tests/math/CMakeLists.txt
  src/tests/math/Makefile.manual
  src/tests/math/test_stdlib_math.fypp
  src/tests/optval/CMakeLists.txt
  src/tests/optval/Makefile.manual
  src/tests/optval/test_optval.fypp
  src/tests/quadrature/CMakeLists.txt
  src/tests/quadrature/Makefile.manual
  src/tests/quadrature/test_simps.fypp
  src/tests/quadrature/test_trapz.fypp
  src/tests/stats/CMakeLists.txt
  src/tests/stats/Makefile.manual
  src/tests/stats/common.fypp
  src/tests/stats/test_distribution_uniform.fypp
  src/tests/stats/test_mean.fypp
  src/tests/stats/test_mean_f03.fypp
  src/tests/stats/test_median.fypp
Labels: reviewers needed, refactoring

#566 Create a call for reviewers pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: meta

#578 Update error in case fypp preprocessor is not found
  CMakeLists.txt
Labels: reviewers needed, build: cmake
