Repository fortran-lang/stdlib, pull requests merged in 2022-05, with the labels that each got.

#656 Add hint for building error with make
  README.md
Labels: documentation, build: make

#655 fixed 32-bit integer overflow in stdlib_io_npy
  src/stdlib_io_npy_load.fypp
  src/stdlib_io_npy_save.fypp
Labels: bug, reviewers needed, topic: IO

#657 Remove support for manual make builds
  .github/workflows/CI.yml
  Makefile.manual
  README.md
  WORKFLOW.md
  src/Makefile.manual
  src/tests/Makefile.manual
  src/tests/Makefile.manual.test.mk
  src/tests/array/Makefile.manual
  src/tests/ascii/Makefile.manual
  src/tests/bitsets/Makefile.manual
  src/tests/hash_functions/Makefile.manual
  src/tests/hash_functions_perf/Makefile.manual
  src/tests/io/Makefile.manual
  src/tests/linalg/Makefile.manual
  src/tests/logger/Makefile.manual
  src/tests/math/Makefile.manual
  src/tests/optval/Makefile.manual
  src/tests/quadrature/Makefile.manual
  src/tests/selection/Makefile.manual
  src/tests/sorting/Makefile.manual
  src/tests/stats/Makefile.manual
  src/tests/string/Makefile.manual
  src/tests/stringlist/Makefile.manual
Labels: build: make
